"""WP-2 to WP-7 schemas

Revision ID: 7abeb26c43ce
Revises: 54dfaa25b857
Create Date: 2026-05-09 01:13:08.322978

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7abeb26c43ce'
down_revision: Union[str, Sequence[str], None] = '54dfaa25b857'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # Clean wipe migration (Day 1 requirement)
    op.execute('TRUNCATE users, sessions, events, orders, cart_items, reviews CASCADE')
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('post_session_survey',
    sa.Column('survey_id', sa.UUID(), nullable=False),
    sa.Column('customer_id', sa.UUID(), nullable=False),
    sa.Column('session_id', sa.UUID(), nullable=False),
    sa.Column('scenario_id', sa.String(length=50), nullable=True),
    sa.Column('survey_lang', sa.String(length=10), nullable=True),
    sa.Column('intent_to_buy', sa.String(length=50), nullable=True),
    sa.Column('completed_purchase', sa.Boolean(), nullable=True),
    sa.Column('abandonment_reason', sa.Text(), nullable=True),
    sa.Column('abandonment_reason_other', sa.Text(), nullable=True),
    sa.Column('mission_completed_self_report', sa.String(length=50), nullable=True),
    sa.Column('mission_recall_text', sa.Text(), nullable=True),
    sa.Column('scenario_realism_score', sa.Integer(), nullable=True),
    sa.Column('overall_realism_score', sa.Integer(), nullable=True),
    sa.Column('free_text', sa.Text(), nullable=True),
    sa.Column('submitted_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['customer_id'], ['users.customer_id'], ),
    sa.ForeignKeyConstraint(['session_id'], ['sessions.session_id'], ),
    sa.PrimaryKeyConstraint('survey_id')
    )
    op.add_column('events', sa.Column('scenario_id', sa.String(length=50), nullable=True))
    op.add_column('events', sa.Column('abandonment_stage', sa.String(length=50), nullable=True))
    op.add_column('events', sa.Column('budget_utilization_pct', sa.Float(), nullable=True))
    op.add_column('events', sa.Column('time_since_session_start_sec', sa.Float(), nullable=True))
    op.add_column('events', sa.Column('image_index', sa.Integer(), nullable=True))
    op.add_column('events', sa.Column('total_images_available', sa.Integer(), nullable=True))
    op.drop_column('events', 'abandonment_status')
    op.add_column('products', sa.Column('discount_ends_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('products', sa.Column('image_count', sa.Integer(), nullable=True))
    op.add_column('products', sa.Column('stock_remaining', sa.Integer(), nullable=True))
    op.add_column('sessions', sa.Column('abandonment_stage', sa.String(length=50), nullable=True))
    op.add_column('sessions', sa.Column('scenario_id', sa.String(length=50), nullable=True))
    op.add_column('sessions', sa.Column('scenario_recall_correct', sa.Boolean(), nullable=True))
    op.add_column('sessions', sa.Column('mission_alignment_score', sa.Float(), nullable=True))
    op.add_column('sessions', sa.Column('mission_completed_inferred', sa.Boolean(), nullable=True))
    op.drop_column('sessions', 'abandonment_status')
    op.add_column('users', sa.Column('credit_balance_initial', sa.Numeric(precision=12, scale=2), nullable=False))
    op.add_column('users', sa.Column('budget_matrix_version', sa.String(length=10), nullable=False))
    op.add_column('users', sa.Column('scenario_id', sa.String(length=50), nullable=False))
    op.add_column('users', sa.Column('scenario_label', sa.String(length=100), nullable=False))
    op.add_column('users', sa.Column('scenario_intent_level', sa.String(length=20), nullable=False))
    op.add_column('users', sa.Column('scenario_text_shown', sa.Text(), nullable=False))
    op.add_column('users', sa.Column('scenario_text_lang', sa.String(length=10), nullable=False))
    op.add_column('users', sa.Column('scenario_text_version', sa.String(length=10), nullable=False))
    op.add_column('users', sa.Column('scenario_acknowledged_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('users', sa.Column('scenario_read_time_sec', sa.Integer(), nullable=True))
    op.add_column('users', sa.Column('device_fingerprint', sa.String(length=256), nullable=True))
    op.add_column('users', sa.Column('lottery_eligible', sa.Boolean(), nullable=True))
    op.add_column('users', sa.Column('contact_email_for_lottery', sa.String(length=255), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'contact_email_for_lottery')
    op.drop_column('users', 'lottery_eligible')
    op.drop_column('users', 'device_fingerprint')
    op.drop_column('users', 'scenario_read_time_sec')
    op.drop_column('users', 'scenario_acknowledged_at')
    op.drop_column('users', 'scenario_text_version')
    op.drop_column('users', 'scenario_text_lang')
    op.drop_column('users', 'scenario_text_shown')
    op.drop_column('users', 'scenario_intent_level')
    op.drop_column('users', 'scenario_label')
    op.drop_column('users', 'scenario_id')
    op.drop_column('users', 'budget_matrix_version')
    op.drop_column('users', 'credit_balance_initial')
    op.add_column('sessions', sa.Column('abandonment_status', sa.BOOLEAN(), autoincrement=False, nullable=True))
    op.drop_column('sessions', 'mission_completed_inferred')
    op.drop_column('sessions', 'mission_alignment_score')
    op.drop_column('sessions', 'scenario_recall_correct')
    op.drop_column('sessions', 'scenario_id')
    op.drop_column('sessions', 'abandonment_stage')
    op.drop_column('products', 'stock_remaining')
    op.drop_column('products', 'image_count')
    op.drop_column('products', 'discount_ends_at')
    op.add_column('events', sa.Column('abandonment_status', sa.BOOLEAN(), autoincrement=False, nullable=True))
    op.drop_column('events', 'total_images_available')
    op.drop_column('events', 'image_index')
    op.drop_column('events', 'time_since_session_start_sec')
    op.drop_column('events', 'budget_utilization_pct')
    op.drop_column('events', 'abandonment_stage')
    op.drop_column('events', 'scenario_id')
    op.drop_table('post_session_survey')
    # ### end Alembic commands ###
