"use client";

/**
 * useInterventionWS — subscribes to the backend WebSocket for real-time
 * intervention messages generated by the LangGraph agent.
 *
 * Usage:
 *   const intervention = useInterventionWS(token);
 *
 * Returns the latest Intervention payload, or null if none yet.
 * Automatically reconnects on disconnect (3 s delay).
 * Sends a "ping" every 30 s to keep the connection alive.
 */

import { useEffect, useRef, useState } from "react";
import tracker from "@/lib/tracker";

export interface Intervention {
  type: string;
  action: string;
  message: string;
  segment: string;
}

const RECONNECT_DELAY_MS = 3_000;
const PING_INTERVAL_MS   = 30_000;

export function useInterventionWS(token: string | null): Intervention | null {
  const [intervention, setIntervention] = useState<Intervention | null>(null);
  const wsRef      = useRef<WebSocket | null>(null);
  const pingRef    = useRef<ReturnType<typeof setInterval> | null>(null);
  const reconnectRef = useRef<ReturnType<typeof setTimeout> | null>(null);
  const activeRef  = useRef(true); // false after cleanup → stop reconnecting

  useEffect(() => {
    if (!token || typeof window === "undefined") return;

    activeRef.current = true;

    const connect = () => {
      if (!activeRef.current) return;

      const sessionId = tracker.getSessionId();
      if (!sessionId) {
        // Tracker not yet initialized — retry shortly
        reconnectRef.current = setTimeout(connect, 500);
        return;
      }

      const apiUrl = process.env.NEXT_PUBLIC_API_URL || "http://localhost:8000";
      const wsUrl  = apiUrl.replace(/^http/, "ws") + `/ws/${sessionId}`;

      const ws = new WebSocket(wsUrl);
      wsRef.current = ws;

      ws.onmessage = (event: MessageEvent) => {
        try {
          const data = JSON.parse(event.data) as Intervention;
          if (data.type === "intervention") {
            setIntervention(data);
          }
        } catch {
          // non-JSON frames (e.g. "pong") — ignore
        }
      };

      ws.onclose = () => {
        if (pingRef.current) clearInterval(pingRef.current);
        if (activeRef.current) {
          reconnectRef.current = setTimeout(connect, RECONNECT_DELAY_MS);
        }
      };

      ws.onopen = () => {
        pingRef.current = setInterval(() => {
          if (ws.readyState === WebSocket.OPEN) ws.send("ping");
        }, PING_INTERVAL_MS);
      };
    };

    // Brief delay so TrackerProvider can initialize the tracker first
    reconnectRef.current = setTimeout(connect, 600);

    return () => {
      activeRef.current = false;
      if (reconnectRef.current) clearTimeout(reconnectRef.current);
      if (pingRef.current) clearInterval(pingRef.current);
      if (wsRef.current) {
        wsRef.current.onclose = null; // prevent auto-reconnect loop
        wsRef.current.close();
      }
    };
  }, [token]);

  return intervention;
}
